export enum DataBatchStatus {
  Pending = 1,
  Processing = 2,
  Completed = 3,
  Canceled = 4,
}

export enum EntryProcessorTypes {
  AccountReceivableFreight = 1,
  AccountReceivableTrucking = 2,
  AccountReceivableFreightCreditNote = 3,
  AccountReceivableTruckingCreditNote = 4,
  LedgerFreightClosingEntry = 5,
  LedgerTruckingClosingEntry = 6,
  AccountPayableFreight = 7,
  AccountPayableTrucking = 8,
  CustodyFreight = 9,
  CustodyTrucking = 10,
  LedgerCashOut = 11,
  LedgerBankOut = 12,
  LedgerVisaOut = 13,
  LedgerCashIn = 14,
  LedgerBankIn = 15,
  LedgerVisaIn = 16,
  VendorFreight = 17,
  VendorTrucking = 18,
  VendorFreightAdjustment = 19,
  VendorTruckingAdjustment = 20,
  CashInFreight = 21,
  CashOutFreight = 22,
  LedgerCustodySettlementEntry = 23,
  LedgerClosingFreightDifference = 24,
  VendorPaymentFreight = 25,
  VendorPaymentTrucking = 26,
}
