import { AccountDimensionsModel } from '@/modules/entry-processor/models/account-dimensions.model';
import { DynDataModel } from '@/modules/entry-processor/models/dyn-data-model';

export class DynAccountReceivableLineDto extends DynDataModel {
  CustomId: number;
  UniqueId?: number;
  FreeTextNumber: string;
  DocumentDate: Date;
  DueDate?: Date;
  CashDiscountDate?: Date;
  InvoiceDate?: Date;
  CustomerAccount: string;
  CustomerReference: string;
  CustomerRequisition: string;
  InvoiceAccount: string;
  HeaderDefaultDimensionDisplayValue: string;
  HeaderFinTagDisplayValue: string;
  DefaultDimensionDisplayValue: string;
  LineFinTagDisplayValue: string;
  LedgerDimensionDisplayValue: string;
  Description: string;
  Quantity: number;
  InvoiceTxt: string;
  UnitPrice: number;
  AmountCur: number;
  SalesTaxGroup: string;
  SalesTaxItemGroup: string;
  OverrideSalesTax: string;
  InclTax: string;
  BillingClassification: string;
  BillingCode: string;
  CashDiscountCode: string;
  MethodOfPayment: string;
  TermsOfPayment: string;
  DirectDebitMandateId: string;
  PostingProfile: string;
  EInvoiceAccountCode: string;
  EInvoiceIsLineSpecific: string;
  CurrencyCode: string;
  TransportationDocumentLineId: string;
  CreditNoteInvoiceRef: string;
}
