trigger: none

jobs:
- deployment: Test
  environment:
    name: 'Contabo Live Server'

  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: none

        - script: |
            hostname
            pwd
            docker --version