/**
 * Represents a Vendor from D365FO's VendorsV3 entity.
 */
export interface D365FOVendor {
  '@odata.etag'?: string;
  dataAreaId: string;
  VendorAccountNumber: string;
  CompanyChainName?: string;
  AddressValidFrom?: string;
  PrimaryLinkedIn?: string;
  Tax1099Type?: string | null;
  CentralBankPurposeCode?: string;
  InventoryProfile?: string;
  PrimaryFaxNumberExtension?: string;
  LineOfBusinessId?: string;
  FactoringVendorAccountNumber?: string;
  NAFCode?: string;
  AddressCity?: string;
  VendorGroupId?: string;
  IsServiceDeliveryAddressBased?: 'Yes' | 'No';
  PersonMiddleName?: string;
  BrazilianIE?: string;
  FixedExchangeRate?: 'Yes' | 'No';
  VendorExceptionGroupId?: string;
  CommercialRegisterName?: string;
  CommercialRegisterInsetNumber?: string;
  FiscalCode?: string;
  PersonBirthMonth?: string;
  CISNationalInsuranceNumber?: string;
  StyleIdPrefix?: string;
  AddressDistrictName?: string;
  PrimaryFacebook?: string;
  NumberSequenceGroupId?: string;
  AddressBrazilianIE?: string;
  SSIVendor?: 'Yes' | 'No';
  StructureDepartment?: string;
  PrimaryContactPersonId?: string;
  VendorKnownAsName?: string;
  OrganizationABCCode?: string;
  WillInvoiceProcessingSummaryUpdatePurchaseOrder?: 'Yes' | 'No';
  AddressCountyId?: string;
  TCSGroup?: string;
  PersonPersonalTitle?: string;
  OverrideSalesTax?: 'Yes' | 'No';
  IsWomanOwner?: 'Yes' | 'No';
  AddressStateId?: string;
  IsMinorityOwned?: 'Yes' | 'No';
  PricePointRoundingType?: string;
  Tax1099FederalTaxId?: string;
  SiretNumber?: string;
  DefaultOffsetLedgerAccountDisplayValue?: string;
  WillReceiptsListProcessingSummaryUpdatePurchaseOrder?: 'Yes' | 'No';
  IsPurchaseConsumed?: 'Yes' | 'No';
  IsReportingTax1099?: 'Yes' | 'No';
  VendorProductHierarchyId?: number;
  IsVendorLocallyOwned?: 'Yes' | 'No';
  VendorInvoiceDeclarationId?: string;
  VendorInvoiceLineMatchingPolicy?: string;
  PrimaryTelexPurpose?: string;
  OrganizationEmployeeAmount?: number;
  BrazilianINSSCEI?: string;
  PaymentId?: string;
  VendorDUNSNumber?: string;
  ElectronicLocationId?: string;
  ChargeVendorGroupId?: string;
  PricePointGroupId?: string;
  IsServiceVeteranOwned?: 'Yes' | 'No';
  FormattedPrimaryAddress?: string;
  DefaultTotalDiscountVendorGroupCode?: string;
  DefaultCashDiscountUsage?: string;
  IsIncomingFiscalDocumentGenerated?: 'Yes' | 'No';
  AddressLocationId?: string;
  PrimaryContactPhoneRecordId?: number;
  PrimaryURLDescription?: string;
  AddressCityInKana?: string;
  BankTransactionType?: string;
  Tax1099NameToUse?: string;
  UniquePopulationRegistryCode?: string;
  AddressBuildingCompliment?: string;
  AddressLatitude?: number;
  ForeignResident?: 'Yes' | 'No';
  PrimaryFaxNumber?: string;
  SalesTaxGroupCode?: string;
  PersonProfessionalSuffix?: string;
  PrimaryContactFaxRecordId?: number;
  OIDNomineeDetails?: string;
  PANNumber?: string;
  PrimaryFaxNumberPurpose?: string;
  PrimaryURLPurpose?: string;
  CISVerificationNumber?: string;
  OrganizationPhoneticName?: string;
  StateInscription?: string;
  BankAccountId?: string;
  VendorType?: string;
  BrazilianNIT?: string;
  AddressTimeZone?: string | null;
  VendorPriceToleranceGroupId?: string;
  Tax1099DoingBusinessAsName?: string;
  CommercialRegisterSection?: string;
  PrimaryFacebookPurpose?: string;
  ColorIdPrefix?: string;
  PersonFirstName?: string;
  TaxOperationCode?: string;
  PriceVendorGroupId?: string;
  AddressLongitude?: number;
  PrimaryURL?: string;
  VendorPartyNumber?: string;
  DefaultPurchaseSiteId?: string;
  CISUniqueTaxPayerReference?: string;
  IsW9Received?: 'Yes' | 'No';
  IsPurchaseOrderChangeRequestOverrideAllowed?: 'Yes' | 'No';
  VendorSearchName?: string;
  RFCFederalTaxNumber?: string;
  IsPrimaryPhoneNumberMobile?: 'Yes' | 'No';
  SalesPriceRounding?: string;
  PersonLastName?: string;
  PrimaryPhoneNumberDescription?: string;
  ZakatRegistrationNumber?: string;
  PersonAnniversaryMonth?: string;
  DIOTVendorType?: string;
  PurchaseWorkCalendarId?: string;
  ExchangeRate?: number;
  DefaultPaymentDayName?: string;
  Tax1099BoxId?: string;
  OnHoldStatus?: 'Yes' | 'No';
  RoundingMethod?: string;
  DefaultDeliveryTermsCode?: string;
  ProductDescriptionVendorGroupId?: string;
  IsOwnerDisabled?: 'Yes' | 'No';
  CreditLimit?: number;
  WithholdingTaxGroupCode?: string;
  HasOnlyTakenBids?: 'Yes' | 'No';
  AddressCountryRegionISOCode?: string;
  Tax1099IdType?: string;
  DUNSNumber?: string;
  CashDiscountCode?: string;
  PrimaryPhoneNumber?: string;
  CreateBarcodeIfNeeded?: 'Yes' | 'No';
  PersonPhoneticMiddleName?: string;
  DefaultInventoryStatusId?: string;
  DefaultPaymentTermsName?: string;
  VendorHoldReleaseDate?: string;
  NameControl?: string;
  IsICMSContributor?: 'Yes' | 'No';
  BrazilianCCM?: string;
  ForeignVendor?: 'Yes' | 'No';
  IsVendorPayingBankPaymentFee?: 'Yes' | 'No';
  InvoiceVendorAccountNumber?: string;
  PurchaseRebateVendorGroupId?: string;
  DIOTCountryCode?: string;
  AddressBrazilianCNPJOrCPF?: string;
  PrimaryPhoneNumberPurpose?: string;
  FiscalDocumentIncomeCode?: string;
  PANStatus?: string;
  OrganizationNumber?: string;
  PaymentTransactionCode?: string;
  AddressStreet?: string;
  BankOrderOfPayment?: string;
  BarcodeNumberSequence?: string;
  PrimaryEmailAddressPurpose?: string;
  IsOneTimeVendor?: 'Yes' | 'No';
  PrimaryEmailAddress?: string;
  IsCUSIPIdentificationNumberApplicable?: 'Yes' | 'No';
  TaxPartnerKind?: string;
  CompositionScheme?: 'Yes' | 'No';
  AddressLocationRoles?: string;
  PrimaryTelex?: string;
  MainContactPersonnelNumber?: string;
  TaxAgent?: 'Yes' | 'No';
  VendorOrganizationName?: string;
  SizeIdPrefix?: string;
  Nationality?: string;
  AddressCountryRegionId?: string;
  PrimaryTwitterDescription?: string;
  PersonProfessionalTitle?: string;
  AddressDescription?: string;
  VendorPaymentFineCode?: string;
  ResidenceForeignCountryRegionId?: string;
  DefaultPaymentScheduleName?: string;
  CompanyType?: string;
  PersonBirthDay?: number;
  LineDiscountVendorGroupCode?: string;
  ForeignVendorTaxRegistrationId?: string;
  WithholdingTaxVendorType?: string;
  FiscalOperationPresenceType?: string;
  WillPurchaseOrderProcessingSummaryUpdatePurchaseOrder?: 'Yes' | 'No';
  PersonHobbies?: string;
  AddressRecordId?: number;
  IsGSTCompositionSchemeEnabled?: 'Yes' | 'No';
  PrimaryFaxNumberDescription?: string;
  DefaultPurchaseOrderPoolId?: string;
  InventoryProfileType?: string;
  ForeignerId?: string;
  PrimaryTwitter?: string;
  BirthPlace?: string;
  IsVendorLocatedInHUBZone?: 'Yes' | 'No';
  CreditRating?: string;
  Notes?: string;
  PrimaryFacebookDescription?: string;
  ArePricesIncludingSalesTax?: 'Yes' | 'No';
  PrimaryTwitterPurpose?: string;
  BuyerGroupId?: string;
  IsForeignEntity?: 'Yes' | 'No';
  CentralBankPurposeText?: string;
  ZakatServiceType?: string;
  DefaultProcumentWarehouseId?: string;
  DIOTOperationType?: string;
  PersonPersonalSuffix?: string;
  VendorPartyType?: string;
  AddressStreetNumber?: string;
  IsChangeManagementActivated?: 'Yes' | 'No';
  BrazilianCNPJOrCPF?: string;
  WillProductReceiptProcessingSummaryUpdatePurchaseOrder?: 'Yes' | 'No';
  CUSIPDetails?: string;
  VendorPortalCollaborationMethod?: string;
  AddressStreetInKana?: string;
  PersonLastNamePrefix?: string;
  LanguageId?: string;
  CUSIPIdentificationNumber?: string;
  MultilineDiscountVendorGroupCode?: string;
  BirthCountyCode?: string;
  PersonPhoneticFirstName?: string;
  AddressValidTo?: string;
  DefaultVendorPaymentMethodName?: string;
  AddressPostBox?: string;
  WillPurchaseOrderIncludePricesAndAmounts?: 'Yes' | 'No';
  PrimaryLinkedInPurpose?: string;
  AddressZipCode?: string;
  PrimaryContactEmailRecordId?: number;
  CISStatus?: string;
  GTAVendor?: 'Yes' | 'No';
  VendorPaymentFinancialInterestCode?: string;
  PrimaryLinkedInDescription?: string;
  TDSGroup?: string;
  ISNationalRegistryNumber?: string;
  PrimaryPhoneNumberExtension?: string;
  DefaultSupplementaryProductVendorGroupId?: string;
  IsPrimaryEmailAddressIMEnabled?: 'Yes' | 'No';
  BrazilianCNAE?: string;
  PersonGender?: string;
  PrimaryContactURLRecordId?: number;
  CISVerificationDate?: string;
  IsW9CheckingEnabled?: 'Yes' | 'No';
  BusinessSegmentCode?: string;
  PaymentFeeGroupId?: string;
  SeparateDivisionId?: string;
  DefaultOffsetAccountType?: string;
  AddressBooks?: string;
  PersonBirthYear?: number;
  IsSmallBusiness?: 'Yes' | 'No';
  NationalRegistryNumberId?: string;
  CurrencyCode?: string;
  DefaultLedgerDimensionDisplayValue?: string;
  SSIValidityDate?: string;
  PersonAnniversaryDay?: number;
  PurchaseOrderConsolidationDayOfMonth?: number;
  DefaultDeliveryModeId?: string;
  BusinessSubsegmentCode?: string;
  PersonMaritalStatus?: string;
  ZakatFileNumber?: string;
  UPSFreightZone?: string;
  IsSubcontractor?: 'Yes' | 'No';
  OIDInvestorType?: string;
  PaymentSpecificationId?: string;
  PreferentialVendor?: 'Yes' | 'No';
  TaxExemptNumber?: string;
  ClearingPeriodPaymentTermsId?: string;
  IsFlaggedWithSecondTIN?: 'Yes' | 'No';
  PersonPhoneticLastName?: string;
  ServiceCategory?: string;
  DestinationCode?: string;
  PrimaryEmailAddressDescription?: string;
  PersonInitials?: string;
  PersonAnniversaryYear?: number;
  OurAccountNumber?: string;
  PANReferenceNumber?: string;
  EnterpriseNumber?: string;
  PrimaryTelexDescription?: string;
  PersonChildrenNames?: string;
  NatureOfAssessee?: string;
  CISCompanyRegistrationNumber?: string;
  IsChangeMangementOverrideByVendorAllowed?: 'Yes' | 'No';
  EthnicOriginId?: string;
  IsWithholdingTaxCalculated?: 'Yes' | 'No';
  IsPublicSector_IT?: 'Yes' | 'No';
  RecId?: number;
}

