/**
 * Represents a Customer from D365FO's Customers entity.
 */
export interface D365FOCustomer {
  '@odata.etag'?: string;
  dataAreaId: string;
  CustomerAccount: string;
  AddressBrazilianCNPJOrCPF?: string;
  PartyType?: string;
  PrimaryContactFaxExtension?: string;
  IsFuelSurchargeApplied?: 'Yes' | 'No';
  SalesTaxGroup?: string;
  AddressCountryRegionId?: string;
  ContactPersonId?: string;
  CustomerPaymentFineCode?: string;
  BirthCountyCode?: string;
  InvoiceAddress?: string;
  PackingMaterialFeeLicenseNumber?: string;
  TransactionPresenceType?: string;
  PrimaryContactTwitter?: string;
  PrimaryContactEmailIsIM?: 'Yes' | 'No';
  InvoiceAddressCity?: string;
  IsFinalUser?: 'Yes' | 'No';
  PrimaryContactEmail?: string;
  DeliveryAddressCounty?: string;
  HasSuframaDiscountPISandCOFINS?: 'Yes' | 'No';
  InvoiceAddressStreet?: string;
  CURPNumber?: string;
  PrimaryContactLinkedInDescription?: string;
  Name?: string;
  DeliveryAddressCountryRegionId?: string;
  ItemCustomerGroupId?: string;
  PersonProfessionalTitle?: string;
  SalesSegmentId?: string;
  IsServiceDeliveryAddressBased?: 'Yes' | 'No';
  PrimaryContactTelexDescription?: string;
  InvoiceAddressDistrictName?: string;
  InvoiceAddressTimeZone?: string | null;
  SalesAccountNumber?: string;
  PrimaryContactFacebookDescription?: string;
  PrimaryContactPhoneIsMobile?: 'Yes' | 'No';
  TCSGroup?: string;
  DeliveryAddressLocationId?: string;
  AddressZipCode?: string;
  GiroTypeProjInvoice?: string;
  LineOfBusinessId?: string;
  OrganizationPhoneticName?: string;
  CreditCardCVC?: string;
  DeliveryAddressCountryRegionISOCode?: string;
  DeliveryAddressValidFrom?: string;
  GiroTypeAccountStatement?: string;
  CalculateWithholdingTax?: 'Yes' | 'No';
  IsRFIDPalletTaggingEnabled?: 'Yes' | 'No';
  ElectronicInvoiceEAN?: string;
  DeliveryFreightZone?: string;
  PrimaryContactFax?: string;
  TaxExemptNumber?: string;
  DeliveryAddressDescription?: string;
  DeliveryAddressLongitude?: number;
  BirthPlace?: string;
  AddressCity?: string;
  PersonInitials?: string;
  CentralBankPurposeCode?: string;
  GiroTypeCollectionletter?: string;
  FullPrimaryAddress?: string;
  OrderEntryDeadline?: string;
  ForeignerId?: string;
  WarehouseIsASNGenerated?: 'Yes' | 'No';
  AddressLongitude?: number;
  PrimaryContactLinkedIn?: string;
  PrimaryContactURL?: string;
  IsFreightAccrued?: 'Yes' | 'No';
  PartyState?: string;
  PartyNumber?: string;
  InvoiceAccount?: string;
  WarehouseFulfillmentRate?: number;
  CentralBankPurposeNotes?: string;
  CollectionsContactPersonId?: string;
  PersonMaritalStatus?: string;
  AddressLocationId?: string;
  PaymentSchedule?: string;
  PrimaryContactTwitterPurpose?: string;
  GiroType?: string;
  InvoiceAddressDescription?: string;
  AddressDistrictName?: string;
  DeliveryTerms?: string;
  NumberSequenceGroup?: string;
  PersonChildrenNames?: string;
  PaymentMethod?: string;
  DeliveryMode?: string;
  PersonProfessionalSuffix?: string;
  OnHoldStatus?: 'Yes' | 'No';
  WarehouseFulfillmentType?: string;
  WarehouseId?: string;
  AccountStatement?: string;
  DestinationCode?: string;
  IRS1099CIndicator?: 'Yes' | 'No';
  FrenchSiret?: string;
  PaymentDay?: string;
  BrazilianNIT?: string;
  FederalIndicator?: string;
  EmployeeResponsibleNumber?: string;
  PersonAnniversaryYear?: number;
  DefaultInventoryStatusId?: string;
  PrimaryContactEmailDescription?: string;
  AddressTimeZone?: string;
  PrimaryContactPhone?: string;
  DeliveryAddressCity?: string;
  InvoiceAddressCounty?: string;
  PANReferenceNumber?: string;
  DeliveryAddressStreet?: string;
  SalesCurrencyCode?: string;
  IsSalesTaxIncludedInPrices?: 'Yes' | 'No';
  BrazilianCNPJOrCPF?: string;
  PaymentFactoringAccount?: string;
  PANNumber?: string;
  PrimaryContactTwitterDescription?: string;
  BrazilianCCM?: string;
  ReceiptEmail?: string;
  TDSGroup?: string;
  MultiLineDiscountCode?: string;
  PersonAnniversaryDay?: number;
  DefaultDimensionDisplayValue?: string;
  SupplementaryItemGroupId?: string;
  IsWithholdingTaxCalculated?: 'Yes' | 'No';
  PaymentSpecification?: string;
  AddressBooks?: string;
  PrimaryContactEmailPurpose?: string;
  SalesDistrict?: string;
  ConsolidationDay?: number;
  IsExpressBillOfLadingAccepted?: 'Yes' | 'No';
  CreditCardAddressVerification?: string;
  AddressState?: string;
  IsExcludedFromCollectionFeeCalculation?: 'Yes' | 'No';
  CustomerPaymentFinancialInterestCode?: string;
  IsTransactionPostedAsShipment?: 'Yes' | 'No';
  IsExternallyMaintained?: 'Yes' | 'No';
  CreditLimitIsMandatory?: 'Yes' | 'No';
  PaymentTermsBaseDays?: number;
  FiscalCode?: string;
  KnownAs?: string;
  PrimaryContactTelex?: string;
  PaymentBankAccount?: string;
  BrazilianIE?: string;
  PreferentialCustomer?: 'Yes' | 'No';
  ReceiptOption?: string;
  FulfillmentErrorTolerance?: string;
  AddressBrazilianIE?: string;
  PersonAnniversaryMonth?: string;
  PrimaryContactPhoneExtension?: string;
  PrimaryContactPhonePurpose?: string;
  ExportSale?: 'Yes' | 'No';
  OrganizationNumber?: string;
  CreditCardAddressVerificationIsAuthorizationVoidedOnFailure?: 'Yes' | 'No';
  InvoiceAddressState?: string;
  ReceiptCalendar?: string;
  DeliveryAddressState?: string;
  StateInscription?: string;
  SalesReturnTaxGroup?: string;
  PrimaryContactURLDescription?: string;
  CustomerWithholdingContributionType?: string;
  IsElectronicInvoice?: 'Yes' | 'No';
  FederalAgencyLocationCode?: string;
  GiroTypeFreeTextInvoice?: string;
  DeliveryAddressValidTo?: string;
  PersonPhoneticMiddleName?: string;
  OrganizationABCCode?: string;
  BrazilianCNAE?: string;
  WithholdingTaxGroupCode?: string;
  NAFCode?: string;
  AddressLatitude?: number;
  TotalDiscountCode?: string;
  PaymentCashDiscount?: string;
  AddressLocationRoles?: string;
  DeliveryAddressDistrictName?: string;
  CreditRating?: string;
  PrimaryContactFacebook?: string;
  InvoiceAddressLongitude?: number;
  LineDiscountCode?: string;
  PartyCountry?: string;
  InvoiceAddressLatitude?: number;
  IsInSuframaRegion?: 'Yes' | 'No';
  IsIncomingFiscalDocumentGenerated?: 'Yes' | 'No';
  SalesMemo?: string;
  ReliefGroupId?: string;
  IsExcludedFromInterestChargeCalculation?: 'Yes' | 'No';
  StatisticsGroupId?: string;
  SalesOrderPoolId?: string;
  IsOrderNumberReferenceUsed?: 'Yes' | 'No';
  AddressValidTo?: string;
  FederalComments?: string;
  PersonGender?: string;
  PaymentTerms?: string;
  PrimaryContactPhoneDescription?: string;
  SalesSubsegmentId?: string;
  CustomerRebateGroupId?: string;
  AddressCounty?: string;
  IsRFIDCaseTaggingEnabled?: 'Yes' | 'No';
  EnterpriseNumber?: string;
  IsICMSContributor?: 'Yes' | 'No';
  InvoiceAddressValidTo?: string;
  DeliveryAddressTimeZone?: string | null;
  InvoiceAddressValidFrom?: string;
  CreditLimit?: number;
  CreditCardAddressVerificationLevel?: string;
  WarehouseIsEntireShipmentFilled?: 'Yes' | 'No';
  PackingDutyLicense?: string;
  NationalRegistryNumber?: string;
  SiteId?: string;
  InvoiceAddressCountryRegionISOCode?: string;
  PrimaryContactURLPurpose?: string;
  ChargesGroupId?: string;
  PanStatus?: string;
  CommissionSalesGroupId?: string;
  NameAlias?: string;
  PrimaryContactFaxPurpose?: string;
  PaymentIdType?: string;
  VendorAccount?: string;
  AddressCountryRegionISOCode?: string;
  ResidenceForeignCountryRegionId?: string;
  RFCNumber?: string;
  PersonHobbies?: string;
  ElectronicLocationId?: string;
  InvoiceAddressZipCode?: string;
  PrimaryContactLinkedInPurpose?: string;
  IsOneTimeCustomer?: 'Yes' | 'No';
  ForeignCustomer?: 'Yes' | 'No';
  CustomerTMAGroupId?: string;
  AddressValidFrom?: string;
  OrganizationNumberOfEmployees?: number;
  CompanyType?: string;
  IsRFIDItemTaggingEnabled?: 'Yes' | 'No';
  CustomerGroupId?: string;
  GiroTypeInterestNote?: string;
  DeliveryAddressZipCode?: string;
  DeliveryReason?: string;
  TaxRegistrationId?: string;
  PaymentUseCashDiscount?: string;
  DiscountPriceGroupId?: string;
  AddressDescription?: string;
  SuframaNumber?: string;
  IdentificationNumber?: string;
  PersonPhoneticFirstName?: string;
  PrimaryContactTelexPurpose?: string;
  DeliveryAddressLatitude?: number;
  InvoiceAddressCountryRegionId?: string;
  PrimaryContactFacebookPurpose?: string;
  CompanyChain?: string;
  BrazilianINSSCEI?: string;
  CommissionCustomerGroupId?: string;
  PrimaryContactFaxDescription?: string;
  NatureOfAssessee?: string;
  WriteoffReason?: string;
  InvoiceAddressLocationId?: string;
  PersonPhoneticLastName?: string;
  LanguageId?: string;
  IsPurchRequestUsed?: 'Yes' | 'No';
  AddressStreet?: string;
  RecId?: number;
}

