export const YARD_SHIPPING_LINE_GROUP_MAP: Record<string, string> = {
  'MSC LINE': 'Msc Egypt',
  'SIDRA LINE': 'Sidra Line',
  'SMCL LINE': 'Sidra Line',
  ORCA: 'Msc Egypt',
  'MLH LINE': 'Msc Egypt',
  'ATHENA SHIPPING LINE': 'Sidra Line',
  ARK: 'Sidra Line',
  'PEAK LINE': 'Peak Line',
  'RAVIAN LINE': 'Sidra Line',
  'VMR LINE': 'Sidra Line',
  ALTUN: 'Altun Egypt',
  'SHIPPING CASTLE': 'Msc Egypt',
  'TURKON LINE': 'Turkon Egypt',
  'OVP LINE': 'Sidra Line',
  SEALEAD: 'Sealead Line',
};

export const YARD_CHARGE_DESCRIPTION_GROUP_MAP: Record<string, string> = {
  'ADMIN FEES': 'Admin Fees',
  'CAR ENTRY FEES': 'Car Entry Fees',
  WASHING: 'Cleaning',
  'WASHING RFR': 'Cleaning',
  CLEANING: 'Cleaning',
  'CLEANING RFR': 'Cleaning',
  'CONTAINER REPAIR': 'Container Repair',
  'CONTAINER SHIFTING': 'Container Shifting',
  'CUSTOM SHIFTING.': 'Custom Shifting',
  'CUSTOM SHIFTING': 'Custom Shifting',
  CUSTOM_SHIFTING: 'Custom Shifting',
  'CUSTOM SHIFTING RFR': 'Custom Shifting',
  'CUSTOM SHIFTING RFR.': 'Custom Shifting',
  'KASHF EST5LAS': 'Kashf Estkhlas',
  'LIFT OFF': 'Lift off',
  'LIFT OFF.': 'Lift off',
  'LIFT OFF RFR': 'Lift off Reefer',
  'LIFT ON': 'Lift on',
  'LIFT ON - LIFT OFF': 'Lift on',
  'LIFT ON - LIFT OFF.': 'Lift on',
  'LIFT ON/OFF (EMPTY)': 'Lift on',
  'LIFT ON RFR': 'Lift on Reefer',
  'LIFT ON - LIFT OFF RFR.': 'Lift on Reefer',
  'LIFT ON - LIFT OFF RFR': 'Lift on Reefer',
  PHOTOCOPY: 'Photo Copy',
  PTI: 'PTI',
  'STORAGE FEES': 'Storage Fees',
  SWEEPING: 'Sweeping',
  'SWEEPING RFR': 'Sweeping',
  'YARD SERVICES.': 'Yard Services',
  'YARD SERVICES': 'Yard Services',
  'DISBURSEMENT CHARGE': 'Disbursement Charge',
  KATABA: 'Kataba',
  'YARD SHIFTING': 'Yard Shifting',
  'YARD SHIFTING MSC': 'Yard Shifting',
  'CLASS A CONTAINER': 'Class A Container',
  'FORM FEES DRY': 'Kashf Estkhlas',
  'FORM FEES REEFER': 'Kashf Estkhlas',
  'YARD NIGHT SHIFT CHARGES': 'Night Shift Charges',
};

export const YARD_COST_CENTER_MAP: Record<string, string> = {
  'Admin Fees': '2401',
  'Car Entry Fees': '2401',
  Cleaning: '2403',
  'Container Repair': '2402',
  'Container Shifting': '2401',
  'Custom Shifting': '2401',
  'Custom Shifting Lift off': '2401',
  'Custom Shifting Lift on': '2401',
  'Kashf Estkhlas': '2501',
  'Lift off': '2401',
  'Lift off Reefer': '2401',
  'Lift on': '2401',
  'Lift on Reefer': '2401',
  'Disbursement Charge': '2401',
  Kataba: '2401',
  'Yard Shifting': '2401',
  'Class A Container': '2401',
  'Photo Copy': '2401',
  PTI: '2401',
  'Storage Fees': '2401',
  Sweeping: '2403',
  'Yard Services': '2401',
  'Night Shift Charges': '2401',
};

export const YARD_BILLING_CLASSIFICATION_MAP: Record<string, string> = {
  'Msc Egypt': 'Yard-Msc Egypt',
  'Sidra Line': 'Yard-Sidra Line',
  'Peak Line': 'Yard-Peak Line',
  'Altun Egypt': 'Yard-AltunEgypt',
  'Turkon Egypt': 'Yard-Turkon Egypt',
  'Sealead Line': 'Yard-Sealead',
};

export const YARD_LOCATION_MAP: Record<string, string> = {
  ALX: '011',
  SHR: '012',
  NHD: '018',
};

export const YARD_COA_MAIN_ACCOUNT_MAP: Record<string, string> = {
  'Admin Fees': '415106',
  'Car Entry Fees': '415106',
  'Class A Container': '415103',
  Cleaning: '415301',
  'Container Repair': '415201',
  'Container Shifting': '415103',
  'Custom Shifting Lift off': '415106',
  'Custom Shifting Lift on': '415106',
  'Disbursement Charge': '415106',
  'Kashf Estkhlas': '415105',
  Kataba: '415106',
  'Lift off': '415101',
  'Lift off Reefer': '415101',
  'Lift on': '415102',
  'Lift on Reefer': '415102',
  'Night Shift Charges': '415106',
  PTI: '415401',
  'Photo Copy': '415106',
  'Storage Fees': '415107',
  Sweeping: '415301',
  'Yard Services': '415106',
  'Yard Shifting': '415106',
};
