export interface ShippingLinesCoaMapping {
  code: string;
  type: string;
  direction: string;
  lineName: string;
  mainAccount: string;
  costCenter: string;
  billingClassification: string;
}

export const SHIPPING_LINES_SUPPORTED_CURRENCIES = new Set([
  'EGP',
  'EUR',
  'GBP',
  'USD',
]);

export const SHIPPING_LINES_COA_MAPPINGS: readonly ShippingLinesCoaMapping[] = [
  {
    code: 'OF - MGS',
    type: 'OCEAN FREIGHT - MGS',
    direction: 'EXP',
    lineName: 'MAGUISA',
    mainAccount: '223511',
    costCenter: '3102',
    billingClassification: 'OF-SH',
  },
  {
    code: 'LIFT ON MG',
    type: 'LIFT ON MGS',
    direction: 'EXP',
    lineName: 'MAGUISA',
    mainAccount: '416104',
    costCenter: '3102',
    billingClassification: 'Inv-SH',
  },
  {
    code: 'THC MGS $',
    type: 'THC USD - MGS',
    direction: 'EXP',
    lineName: 'MAGUISA',
    mainAccount: '416104',
    costCenter: '3102',
    billingClassification: 'Inv-SH',
  },
  {
    code: 'TELEX MGS',
    type: 'TELEX MGS',
    direction: 'EXP',
    lineName: 'MAGUISA',
    mainAccount: '416104',
    costCenter: '3102',
    billingClassification: 'Inv-SH',
  },
  {
    code: 'THC MGS',
    type: 'THC MGS',
    direction: 'EXP',
    lineName: 'MAGUISA',
    mainAccount: '416104',
    costCenter: '3102',
    billingClassification: 'Inv-SH',
  },
  {
    code: 'CONTRA MGS',
    type: 'CONTRACTUAL REVENUE MGS',
    direction: 'EXP',
    lineName: 'MAGUISA',
    mainAccount: '416104',
    costCenter: '3102',
    billingClassification: 'Inv-SH',
  },
  {
    code: '50300',
    type: 'DEMURRAGE - IMP',
    direction: 'IMP',
    lineName: 'RCL',
    mainAccount: '223504',
    costCenter: '3101',
    billingClassification: 'OF-SH',
  },
  {
    code: '50300',
    type: 'DEMURRAGE - EXP',
    direction: 'EXP',
    lineName: 'RCL',
    mainAccount: '223504',
    costCenter: '3101',
    billingClassification: 'OF-SH',
  },
  {
    code: 'CUSTOM PEN',
    type: 'CUSTOM PENALTY',
    direction: 'EXP',
    lineName: 'RCL',
    mainAccount: '223504',
    costCenter: '3101',
    billingClassification: 'OF-SH',
  },
  {
    code: '59978',
    type: 'THIRD PARTY CLAIM, P',
    direction: 'IMP',
    lineName: 'RCL',
    mainAccount: '223504',
    costCenter: '3101',
    billingClassification: 'OF-SH',
  },
  {
    code: '001F',
    type: 'OCEAN FREIGHT',
    direction: 'IMP',
    lineName: 'RCL',
    mainAccount: '223505',
    costCenter: '3101',
    billingClassification: 'OF-SH',
  },
  {
    code: '001F',
    type: 'OCEAN FREIGHT CYCY',
    direction: 'EXP',
    lineName: 'RCL',
    mainAccount: '223506',
    costCenter: '3101',
    billingClassification: 'OF-SH',
  },
  {
    code: '10690',
    type: 'TML HANDLING IMP',
    direction: 'IMP',
    lineName: 'RCL',
    mainAccount: '416101',
    costCenter: '3101',
    billingClassification: 'Inv-SH',
  },
  {
    code: '22890',
    type: 'CONTAINER SERVICE',
    direction: 'IMP',
    lineName: 'RCL',
    mainAccount: '416101',
    costCenter: '3101',
    billingClassification: 'Inv-SH',
  },
  {
    code: '10790',
    type: 'TML HANDLING EXP',
    direction: 'EXP',
    lineName: 'RCL',
    mainAccount: '416102',
    costCenter: '3101',
    billingClassification: 'Inv-SH',
  },
  {
    code: '30490',
    type: 'LIFT OFF CHARGE',
    direction: 'IMP',
    lineName: 'RCL',
    mainAccount: '416103',
    costCenter: '3101',
    billingClassification: 'Inv-SH',
  },
  {
    code: '30190',
    type: 'EQ MANAGEMENT',
    direction: 'IMP',
    lineName: 'RCL',
    mainAccount: '416103',
    costCenter: '3101',
    billingClassification: 'Inv-SH',
  },
  {
    code: '41790',
    type: 'FACILITATION CHARGE',
    direction: 'IMP',
    lineName: 'RCL',
    mainAccount: '416103',
    costCenter: '3101',
    billingClassification: 'Inv-SH',
  },
  {
    code: '30390',
    type: 'LIFT ON CHARGE',
    direction: 'EXP',
    lineName: 'RCL',
    mainAccount: '416103',
    costCenter: '3101',
    billingClassification: 'Inv-SH',
  },
  {
    code: '40090',
    type: 'D/O FEES',
    direction: 'IMP',
    lineName: 'RCL',
    mainAccount: '416103',
    costCenter: '3101',
    billingClassification: 'Inv-SH',
  },
  {
    code: '40690',
    type: 'B/L SURRENDER',
    direction: 'EXP',
    lineName: 'RCL',
    mainAccount: '416104',
    costCenter: '3101',
    billingClassification: 'Inv-SH',
  },
  {
    code: '41490',
    type: 'AMENDMENT FEE EXP',
    direction: 'EXP',
    lineName: 'RCL',
    mainAccount: '416104',
    costCenter: '3101',
    billingClassification: 'Inv-SH',
  },
  {
    code: '31690',
    type: 'SEAL RECOVERY CHARGE',
    direction: 'EXP',
    lineName: 'RCL',
    mainAccount: '416104',
    costCenter: '3101',
    billingClassification: 'Inv-SH',
  },
  {
    code: '41790',
    type: 'FACILITATION CHARGE',
    direction: 'EXP',
    lineName: 'RCL',
    mainAccount: '416104',
    costCenter: '3101',
    billingClassification: 'Inv-SH',
  },
  {
    code: '30590',
    type: 'STORE RENT,',
    direction: 'EXP',
    lineName: 'RCL',
    mainAccount: '416106',
    costCenter: '3101',
    billingClassification: 'Inv-SH',
  },
  {
    code: '15590',
    type: 'LATE RECEIVAL FEE,',
    direction: 'EXP',
    lineName: 'RCL',
    mainAccount: '416106',
    costCenter: '3101',
    billingClassification: 'Inv-SH',
  },
  {
    code: '10890',
    type: 'SHUTOUT, RENOMINATION,(A)',
    direction: 'EXP',
    lineName: 'RCL',
    mainAccount: '416106',
    costCenter: '3101',
    billingClassification: 'Inv-SH',
  },
  {
    code: '11100',
    type: 'CHANGE OF DESTINATION',
    direction: 'EXP',
    lineName: 'RCL',
    mainAccount: '416106',
    costCenter: '3101',
    billingClassification: 'Inv-SH',
  },
  {
    code: '11590',
    type: 'SHIFTING CHARGE,',
    direction: 'EXP',
    lineName: 'RCL',
    mainAccount: '416106',
    costCenter: '3101',
    billingClassification: 'Inv-SH',
  },
  {
    code: '10090',
    type: 'CHANGE OF STATUS',
    direction: 'EXP',
    lineName: 'RCL',
    mainAccount: '416106',
    costCenter: '3101',
    billingClassification: 'Inv-SH',
  },
  {
    code: 'CONTRACT R',
    type: 'CONTRACTUAL REVENUE RCL',
    direction: 'EXP',
    lineName: 'RCL',
    mainAccount: '416202',
    costCenter: '3101',
    billingClassification: 'Inv-SH',
  },
  {
    code: 'CUSTOM PEN',
    type: 'CUSTOM PENALTY FEES',
    direction: 'EXP',
    lineName: 'RCL',
    mainAccount: '223504',
    costCenter: '3101',
    billingClassification: 'OF-SH',
  },
  {
    code: '001F',
    type: 'OCEAN FREIGHT',
    direction: 'IMP',
    lineName: 'VANUDEN',
    mainAccount: '223510',
    costCenter: '3103',
    billingClassification: 'OF-SH',
  },
  {
    code: 'THC VUS',
    type: 'THC RORO',
    direction: 'IMP',
    lineName: 'VANUDEN',
    mainAccount: '416101',
    costCenter: '3103',
    billingClassification: 'Inv-SH',
  },
  {
    code: 'CONTRACT',
    type: 'CONTRACTUAL REVENUE VUS',
    direction: 'EXP',
    lineName: 'VANUDEN',
    mainAccount: '416202',
    costCenter: '3103',
    billingClassification: 'Inv-SH',
  },
  {
    code: 'SECURITY',
    type: 'SECURITY CHARGES',
    direction: 'IMP',
    lineName: 'VANUDEN',
    mainAccount: '416301',
    costCenter: '3104',
    billingClassification: 'Inv-SH',
  },
  {
    code: 'SHIFT',
    type: 'NIGHT-SHIFT VUS',
    direction: 'EXP',
    lineName: 'VANUDEN',
    mainAccount: '416301',
    costCenter: '3103',
    billingClassification: 'Inv-SH',
  },
  {
    code: 'SHIFT',
    type: 'NIGHT-SHIFT VUS',
    direction: 'IMP',
    lineName: 'VANUDEN',
    mainAccount: '416301',
    costCenter: '3103',
    billingClassification: 'Inv-SH',
  },
  {
    code: 'O/F VUS',
    type: 'OCEAN FREIGHT VUS',
    direction: 'IMP',
    lineName: 'VANUDEN',
    mainAccount: '223510',
    costCenter: '3103',
    billingClassification: 'OF-SH',
  },
  {
    code: 'CTR MGS',
    type: 'CONTAINER SERVICE',
    direction: 'EXP',
    lineName: 'MAGUISA',
    mainAccount: '223511',
    costCenter: '3102',
    billingClassification: 'OF-SH',
  },
  {
    code: 'BL MGS',
    type: 'BL MGS',
    direction: 'EXP',
    lineName: 'MAGUISA',
    mainAccount: '416104',
    costCenter: '3102',
    billingClassification: 'Inv-SH',
  },
  {
    code: 'STORAGE',
    type: 'STORAGE',
    direction: 'EXP',
    lineName: 'MAGUISA',
    mainAccount: '416104',
    costCenter: '3102',
    billingClassification: 'Inv-SH',
  },
  {
    code: '10990',
    type: 'COST RECOVERY CHARGE',
    direction: 'EXP',
    lineName: 'RCL',
    mainAccount: '416107',
    costCenter: '3101',
    billingClassification: 'Inv-SH',
  },
  {
    code: '001F',
    type: 'OCEAN FREIGHT CYCY',
    direction: 'IMP',
    lineName: 'RCL',
    mainAccount: '223505',
    costCenter: '3101',
    billingClassification: 'OF-SH',
  },
  {
    code: 'O/F DCU',
    type: 'OCEAN FREIGHT DCU',
    direction: 'IMP',
    lineName: 'VANUDEN',
    mainAccount: '223510',
    costCenter: '3103',
    billingClassification: 'OF-SH',
  },
];

export const SHIPPING_LINES_CHARGE_CODE_MAPPINGS: Readonly<
  Record<string, string>
> = {
  'CHANGE OF STATUS, (A)': '02001',
  'TML HANDLING IMP': '02002',
  'عوائد تفريغ': '02003',
  'TML EXP': '02004',
  'TML HANDLING EXP': '02005',
  'SHUTOUT, RENOMINATION,(A': '02006',
  'CHANGE OF DESTINATION FEE': '02007',
  'SHIFTING CHARGE': '02008',
  'LATE RECEIVAL FEE,': '02009',
  'CONTAINER SERVICE': '02010',
  'EQ MANAGEMENT': '02011',
  'LIFT ON CHARGES': '02012',
  'DELIVERY ORDER': '02013',
  'LIFT OFF': '02014',
  'STORE RENT,': '02015',
  'SEAL RECOVERY CHARGE': '02016',
  'SHUT OUT': '02017',
  'B/L SURRENDER': '02018',
  'B/L AMENDMENT FEE': '02019',
  FACILITATIONCHARGE: '02020',
  'DEMURRAGE FEES غرامات': '02021',
  'DETENTION FEES غرامات': '02022',
  BAF: '02023',
  'EMERGENCY BUNKER SURCH': '02024',
  'LS GO GREEN RECOVERY': '02025',
  'O/F': '02026',
  'OCEAN FREIGHT CYCY FCL20': '02027',
  'OCEAN FREIGHT CYCY FCL40': '02028',
  'RISK PREMIUM': '02029',
  'SECURITY CHARGE, P': '02030',
  'B/L AMENDMENT FEE, P': '02031',
  'CONTAINER IMBALANCE CHRG': '02032',
  'FACILITATION CHARGE, A': '02033',
  'OCEAN FREIGHT CYCD FCL20': '02034',
  'OFFICIAL RECEIPT': '02035',
  'SHUT OUT/RENOMINATION': '02036',
  'COC INB COMMISSION': '02037',
  'COC OUB COMMISSION': '02038',
  'COC T/S COMMISSION': '02039',
  'DND COLLECTION COMMISSION': '02040',
  'INB CTR MONITORING FEE': '02041',
  تخزين: '02042',
  'مصاريف إدارية': '02043',
  'NIGHT-SHIFT': '02044',
  'OTHERS IMP أخرى': '02045',
  'إجراءات تخزين': '02046',
  'إذن تسليم': '02047',
  شرطة: '02048',
  'عروض و إجراءات جمركية': '02049',
  'فحص و معاينة': '02050',
  'مصاريف تفريغ': '02051',
  'مصاريف نقل': '02052',
  ملاحظة: '02053',
  'ملاحظة صرف': '02054',
  'هيئة ميناء': '02055',
  SEAFREIGHT: '02056',
  'BOOKING COMMISSION': '02057',
  'HANDLING COMMISSION': '02058',
  'THIRD PARTY CLAIM, P': '02059',
  'ADMIN CHARGES, A': '02060',
  'DOCUMENTATION FEE': '02061',
  'THC USD': '02062',
  'TELEX RELEASE': '02063',
  THC: '02064',
  'CONTRACTUAL REVENUE': '02065',
  'CUSTOM PENALTY': '02066',
  STORAGE: '02067',
  'BL FEES': '02068',
  'REEFER SURCHARGE': '02069',
  'COST RECOVERY CHARGE': '02070',
  'ADDITIONAL OCEAN FREIGHT': '02071',
  'SEA FREIGHT IMP.': '02072',
  'SOC OUTBOUND EMPTY': '02073',
  'COURIER FEES': '02061',
  'B/L': '02031',
};
